# Generated by Django 4.0.4 on 2022-04-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_movies_image', models.ImageField(blank=True, null=True, upload_to='main_movies_image')),
                ('date_of_issue', models.DateField()),
                ('country', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('Боевик', 'Боевик'), ('Камедия', 'Камедия'), ('Фантастика/фэнтези', 'Фантастика/фэнтези'), ('Мультфильмы', 'Мультфильмы'), ('Драма/мелодрама', 'Драма/мелодрама'), ('Ужасы', 'Ужасы'), ('Детектив/Триллеры', 'Детектив/Триллеры'), ('Документальные', 'Документальные'), ('Сериалы', 'Сериалы')], default='Боевик', max_length=250)),
                ('voice_acting', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_category', to='categories.category')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movie_image/')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_image', to='movies.movies')),
            ],
            options={
                'verbose_name': 'Картинка фильмы',
                'verbose_name_plural': 'Картинки фильмов',
            },
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
