# Generated by Django 4.0.4 on 2022-04-29 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieimage',
            options={'verbose_name': 'Картинка фильма', 'verbose_name_plural': 'Картинки фильмов'},
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_movie_image', models.ImageField(blank=True, null=True, upload_to='main_movie_image')),
                ('year_of_issue', models.DateField()),
                ('genre', models.CharField(choices=[('Боевики', 'Боевики'), ('Комедии', 'Комедии'), ('Фантастика/фэнтези', 'Фантастика/фэнтези'), ('Мультфильмы', 'Мультфильмы'), ('Драма/мелодрама', 'Драма/мелодрама'), ('Ужасы', 'Ужасы'), ('Детектив/Триллеры', 'Детектив/Триллеры'), ('Документальные', 'Документальные')], default='Боевики', max_length=250)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_category', to='categories.category')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_comment', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_image', to='movies.movie'),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
