# Generated by Django 4.0.4 on 2022-05-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('birth', models.DateField()),
                ('position', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актёры',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.IntegerField(blank=True, default=1, verbose_name='Возрастное ограничение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director_film',
            field=models.CharField(blank=True, max_length=55, verbose_name='Режисёр фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=3, verbose_name='Рейтинг'),
        ),
    ]
