# Generated by Django 4.0.4 on 2022-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_setting_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('signature', models.ImageField(upload_to='signature/')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
