# Generated by Django 4.0.4 on 2022-05-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='position',
        ),
        migrations.RemoveField(
            model_name='about',
            name='signature',
        ),
    ]
