# Generated by Django 4.0.4 on 2022-05-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_about_position_remove_about_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='about_image/'),
            preserve_default=False,
        ),
    ]
