# Generated by Django 4.0.4 on 2022-05-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_aboutimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutimage',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='aboutimage',
            name='history',
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='about_image', to='settings.about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(default=1, upload_to='about_image/'),
            preserve_default=False,
        ),
    ]
